# Generated by Django 4.1 on 2023-08-02 11:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Желаемая дата записи')),
                ('time', models.TimeField(verbose_name='Желаемое время записи')),
                ('actual_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время записи')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя')),
                ('status', models.CharField(choices=[('Checked', 'Не обработано'), ('Allowed', 'Принято'), ('Rejected', 'Отклонено')], default='Checked', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'app_feedback',
                'ordering': ['-time_create'],
            },
        ),
    ]
