# Generated by Django 4.1 on 2023-08-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование производителя')),
            ],
            options={
                'verbose_name': 'Производтель товара',
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа товара'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=1, help_text='Выберете группу', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.group', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=1, help_text='Выберете производителя', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.manufacturer', verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
