# Generated by Django 4.1 on 2023-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_manufacturer_alter_group_options_remove_group_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа товара', 'verbose_name_plural': 'Группа товаров'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Картинка товара', 'verbose_name_plural': 'Картинки товаров'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производтель товара', 'verbose_name_plural': 'Производтель товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In_stock', 'Есть в наличии'), ('Absent', 'Временно отсутсвует'), ('On_my_way', 'В пути')], default='IN_STOCK', max_length=10, verbose_name='Статус'),
        ),
    ]
